server:
  port: 8889

spring:
  application:
    name: weichat-comments

  #连接数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/meituan?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

  #Redis数据库
  redis:
    database: 0
    host: 127.0.0.1

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml


#将自己注册到eureka上
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
